version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get install gnupg2 --yes
      - rm -rf /var/lib/apt/lists/*
  pre_build:
    commands:
      - aws s3 cp "${MAVEN_GPG_S3_URI}" "${HOME}/.m2/maven-private-key.asc"
      - gpg --version
      - gpg --list-keys
      - gpg --import "${HOME}/.m2/maven-private-key.asc"
      - gpg --list-keys
#      - printenv
  build:
    commands:
      - mvn install deploy
